POKY_BBLAYERS_CONF_VERSION = "2"
BBPATH = "${TOPDIR}"
BBFILES ?= ""

BSPDIR := "${@os.path.abspath(os.path.join(d.getVar('FILE'), '../../..'))}"

BBLAYERS ?= " \
  ${BSPDIR}/poky/meta \
  ${BSPDIR}/poky/meta-poky \
  ${BSPDIR}/poky/meta-yocto-bsp \
  ${BSPDIR}/meta-raspberrypi \
  ${BSPDIR}/meta-robot \
  /home/roy/Embebidos/Proyecto_1/CE1113-Robot_Aspiradora/src/os/yocto/meta-openembedded/meta-oe \
  /home/roy/Embebidos/Proyecto_1/CE1113-Robot_Aspiradora/src/os/yocto/meta-openembedded/meta-python \
  /home/roy/Embebidos/Proyecto_1/CE1113-Robot_Aspiradora/src/os/yocto/meta-openembedded/meta-multimedia \
  /home/roy/Embebidos/Proyecto_1/CE1113-Robot_Aspiradora/src/os/yocto/meta-openembedded/meta-networking \
  "
