#!/bin/bash

# Limpiar la terminal
clear

# Obtiene la ruta absoluta de la carpeta donde está el script
URL="http://localhost:8080"

echo "==========================================="
echo "🌐 LANZANDO INTERFAZ DESDE ORIGEN LOCAL"
echo "URL: $URL"
echo "==========================================="

# Abrir el archivo. Se usa la ruta absoluta calculada dinámicamente
if command -v xdg-open > /dev/null; then
    xdg-open "$URL"
else
    echo "Abre manualmente: $URL"
fi